language: julia
os:
    - linux
julia:
    - release
    - nightly
sudo: false
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Docile"); Pkg.test("Docile"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Docile")); include(joinpath("test", "coverage.jl"))'
